services:
  mongo:
    image: mongo:7.0
    container_name: mongo-profiler-samples
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: profiler_samples
    volumes:
      - mongo-profiler-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mongo-profiler-sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "DevOnly_Str0ng!Pass"
    volumes:
      - mongo-profiler-sqlserver-data:/var/opt/mssql


volumes:
  mongo-profiler-data:
  mongo-profiler-sqlserver-data:
